name: Validate Delta package
description: validate

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'SF/force-app/**'

jobs:
  validate-package:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
        -   name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 2

        -   name: Install Node
            uses: actions/setup-node@v3
            with:
                node-version: 18

        -   name: App npm global binaries to PATH
            run: |
                export PATH=$(npm bin --global):$PATH
                echo "Now Path: $PATH"

        -   name: Install Salesforce CLI
            run: |
                npm install @salesforce/cli --global 

        -   name: Install sfdx-git-delta
            run: |
                echo Y | sfdx plugins:install sfdx-git-delta
                sfdx plugins

        -   name: Dev login sf
            run: |
                echo "${{secrets.SERVER_KEY}}" >server.key
                sf org login jwt --username ${{secrets.USER_NAME}} --jwt-key-file server.key  --client-id ${{secrets.CONSUMER_KEY}}  --instance-url  ${{vars.DEV_URL}}  --set-default
                rm -f server.key

        -   name: Generate delta package
            run: |
                mkdir changed-sources
                sfdx sgd source delta --to "HEAD" --from "HEAD~1" --output-dir changed-sources/ --generate-delta --source-dir ./SF/force-app


        -   name: Validate delta sf packages
            run: |
                # cp -R ./SF/* changed-sources/

                # # Remove the original directory inside changed-sources if needed
                # rm -rf changed-sources/SF

                # # List the contents of changed-sources to verify structure
                ls -a changed-sources/SF
                sf project deploy validate --source-dir changed-sources/SF/force-app --test-level RunLocalTests